[package]
name = "quoll_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = "symbols"

[dependencies]
napi = { version = "3.9.1", features = ["napi8"] }
napi-derive = "3.5.6"
oxc_allocator = "0.144.0"
oxc_ast = "0.144.0"
oxc_ast_visit = "0.144.0"
oxc_codegen = "0.144.0"
oxc_parser = "0.144.0"
oxc_semantic = "0.144.0"
oxc_sourcemap = "8.0.1"
oxc_span = "0.144.0"
oxc_str = "0.144.0"
oxc_transformer = "0.144.0"

[build-dependencies]
napi-build = "2.3.2"
